version: '3'
services:
  database:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: it_tools

  create_database:
    image: postgres:12-alpine
    container_name: it_tools_database_creator
    restart: on-failure
    command: psql -h postgres -U postgres -f /custom_scripts/CreateDatabase.sql
    depends_on:
      - database
    environment:
      PGPASSWORD: postgres
      PGUSER: postgres
    volumes:
      - ./scripts/:/custom_scripts
